name: CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - master

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        run: rustup show active-toolchain
      - uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/cargo-binstall@main
      - uses: jdx/mise-action@v2
        with:
          experimental: true

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun lint:check

      - name: Format
        run: bun format:check

      - name: Run tests
        run: bun test
